FROM php:7.3-fpm

MAINTAINER grano22@outlook.com

RUN apt-get update -y && apt-get upgrade -y
    
RUN apt-get install -y libpq-dev

RUN docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql
RUN docker-php-ext-install pdo pgsql pdo_mysql pdo_pgsql && docker-php-ext-enable pdo pdo_mysql pdo_pgsql

RUN docker-php-ext-install mysqli sysvsem && docker-php-ext-enable mysqli sysvsem

#RUN echo "localhost localhost.localdomain" >> /etc/hosts